# Author: Michael Vinh Xuan Thanh
version: 2.1

#####################
# Common Definitions
#####################
orbs:
  aws-s3: circleci/aws-s3@2.0.0

aliases:
  - &project_dir "~/mvxt"
  - &bucket_name "s3://mvxt.me"

executors:
  node_exec:
    docker:
      - image: cimg/node:14.15.3
    working_directory: *project_dir

############
# Workflows
############
workflows:
  version: 2.1
  primary:
    jobs:
      - build
      - approve_deploy:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          context: mvxt-prod
          requires:
            - approve_deploy
          filters:
            branches:
              only: master

##################
# Job Definitions
##################
jobs:
  build:
    executor: node_exec
    steps:
      - checkout
      - run:
          name: Install Git LFS and pull images
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get update && sudo apt-get install -y git-lfs
            git lfs install
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com > ~/.ssh/known_hosts
            ssh git@github.com git-lfs-authenticate "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" download
            git lfs pull
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - restore_cache:
          keys:
            - next-dependencies-{{ .Branch }}
            - next-dependencies-
      - run:
          name: Install node modules
          command: |
            yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build next.js app and export static website files
          command: yarn build
      - save_cache:
          key: next-dependencies-{{ .Branch }}
          paths:
            - .next/cache
      - run:
          name: Remove extension from non-index pages WTF S3
          command: |
            pages=$(ls ../pages)

            for page in $pages; do
              no_ext=$(echo $page | cut -f 1 -d '.');

              if [ "$no_ext" != "404" ] && [ "$no_ext" != "_app" ] && [ "$no_ext" != "index" ]; then
                mkdir -p "$no_ext";
                mv ${no_ext}.html ${no_ext}/index.html;
              fi
            done
          working_directory: out
      - store_artifacts:
          path: out
      - persist_to_workspace:
          root: .
          paths: out

  deploy:
    docker:
      - image: cimg/python:3.9.1
    working_directory: *project_dir
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: out
          to: *bucket_name
          arguments: '--delete'
