# Author: Michael Vinh Xuan Thanh
version: 2.1

#####################
# Common Definitions
#####################
orbs:
  aws-s3: circleci/aws-s3@2.0.0

aliases:
  - &project_dir "~/mvxt"
  - &bucket_name "s3://mvxt.me"

executors:
  node_exec:
    docker:
      - image: cimg/node:14.15.3
    working_directory: *project_dir

############
# Workflows
############
workflows:
  version: 2.1
  primary:
    jobs:
      - build
      - approve_deploy:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          context: mvxt-prod
          requires:
            - approve_deploy
          filters:
            branches:
              only: master

##################
# Job Definitions
##################
jobs:
  build:
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install node modules
          command: |
            yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build next.js app and export static website files
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: out

  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: *project_dir
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: out
          to: *bucket_name
          arguments: '--delete'
